
import React, { useState } from 'react';

interface ControlsProps {
  onGenerate: (description: string) => void;
  isLoading: boolean;
}

const Controls: React.FC<ControlsProps> = ({ onGenerate, isLoading }) => {
  const [input, setInput] = useState('a military old english sheepdog with tactical gear');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (input.trim() && !isLoading) {
      onGenerate(input);
    }
  };

  const templates = [
    { label: "Sheepdog", value: "a military old english sheepdog with tactical gear" },
    { label: "Tactical Fox", value: "a sleek desert fox in high-tech special ops armor" },
    { label: "Rambo Raccoon", value: "a rugged raccoon wearing Rambo-style headbands and belts" },
  ];

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <div className="space-y-1.5">
        <label className="text-xs font-bold text-slate-400 uppercase tracking-widest">Skin Blueprint</label>
        <textarea
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="Describe your furry warrior..."
          className="w-full h-32 bg-slate-900 border border-slate-700 rounded-xl p-4 text-sm focus:outline-none focus:ring-2 focus:ring-purple-500 transition-all resize-none"
          disabled={isLoading}
        />
      </div>

      <div className="flex flex-wrap gap-2">
        {templates.map((t) => (
          <button
            key={t.label}
            type="button"
            onClick={() => setInput(t.value)}
            className="text-[10px] bg-slate-700/50 hover:bg-slate-700 px-3 py-1 rounded-full border border-slate-600 transition-colors uppercase font-bold"
            disabled={isLoading}
          >
            {t.label}
          </button>
        ))}
      </div>

      <button
        type="submit"
        disabled={isLoading || !input.trim()}
        className="btn-fortnite w-full py-4 rounded-xl font-black uppercase text-xl italic tracking-tighter disabled:opacity-50 disabled:transform-none shadow-lg shadow-purple-600/20"
      >
        {isLoading ? (
          <span className="flex items-center justify-center gap-2">
            <i className="fa-solid fa-spinner animate-spin"></i>
            Deploying...
          </span>
        ) : (
          "Generate Skin"
        )}
      </button>
      
      <p className="text-[10px] text-slate-500 text-center italic">
        Requires 0 V-Bucks. Generated by Gemini 2.5 Flash.
      </p>
    </form>
  );
};

export default Controls;
